version: "3"
services:
    web:
        build: .
        ports:
            - "8083:8083"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "testing"
            ACCEPT_EULA: "Y"