version: "3.8"
services:
    web:
        build: .
        ports:
            - "8081:8081"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                aliases:
                    - web.internal.visualsanity.io
    
    rabbitmq:
        image: 'rabbitmq:3.8.4-management-alpine'
        ports:
            - "5672:5672"
            - "15672:15672"
    
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "Test1ng!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            default:
                aliases:
                    - db.internal.visualsanity.io

networks:
    default:
        driver: bridge