version: "3.8"

services:
    battleship.statistics:
        image: ${DOCKER_REGISTRY-}battleshipstatistics
        build:
          context: .
          dockerfile: Battleship.Statistics/Dockerfile
        container_name: battleship.Statistics
        ports:
            - "8084:8084"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.8
                aliases:
                    - statistics.internal.visualsanity.io

    battleship.scoreboard:
        image: ${DOCKER_REGISTRY-}battleshipscoreboard
        build:
          context: .
          dockerfile: Battleship.Scoreboard/Dockerfile
        container_name: battleship.Scoreboard
        ports:
            - "8083:8083"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.7
                aliases:
                    - scoreboard.internal.visualsanity.io

    battleship.game:
        image: ${DOCKER_REGISTRY-}battleshipgame
        build:
          context: .
          dockerfile: Battleship.Game/Dockerfile
        container_name: battleship.Game
        ports:
            - "8082:8082"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.6
                aliases:
                    - game.internal.visualsanity.io

    battleship.audit:
        image: ${DOCKER_REGISTRY-}battleshipaudit
        build:
          context: .
          dockerfile: Battleship.Audit/Dockerfile
        container_name: battleship.audit
        ports:
            - "8086:8086"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.5
                aliases:
                    - audit.internal.visualsanity.io

    battleship.player:
        image: ${DOCKER_REGISTRY-}battleshipplayer
        build: 
            context: .
            dockerfile: Battleship.Audit/Dockerfile
        container_name: battleship.player
        ports:
            - "8081:8081"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.4
                aliases:
                    - player.internal.visualsanity.io
    
    rabbitmq:
        image: 'rabbitmq:3.8.4-management-alpine'
        container_name: battleship.rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        networks:
            default:
                ipv4_address: 172.19.0.3
                aliases:
                    - messaging.internal.visualsanity.io
    
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: battleship.sqlserver
        environment:
            SA_PASSWORD: "Test1ng!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        hostname: db.internal.visualsanity.io
        networks:
            default:
                ipv4_address: 172.19.0.2
                aliases:
                    - db.internal.visualsanity.io

networks:
    default:
        ipam:
            driver: bridge
            config:
               - subnet: "172.19.0.0/20"