version: "3.8"

services:

    battleship.web:
        image: ${DOCKER_REGISTRY-}battleshipweb
        restart: on-failure
        build:
          context: .
          dockerfile: Battleship.Microservice.Web/Dockerfile
        container_name: battleship.web
        ports:
            - "80:80"
        depends_on:
            - db
            - rabbitmq
        networks:
            default:
                ipv4_address: 172.19.0.10
                aliases:
                    - web.internal.visualsanity.io

    battleship.statistics:
        image: ${DOCKER_REGISTRY-}battleshipstatistics
        restart: on-failure
        build:
          context: .
          dockerfile: Battleship.Statistics/Dockerfile
        container_name: battleship.statistics
        ports:
            - "8084:8084"
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["/app/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "Battleship.Statistics.dll"]
        networks:
            default:
                ipv4_address: 172.19.0.8
                aliases:
                    - statistics.internal.visualsanity.io

    battleship.scorecard:
        image: ${DOCKER_REGISTRY-}battleshipscorecard
        restart: on-failure
        build:
          context: .
          dockerfile: Battleship.ScoreCard/Dockerfile
        container_name: battleship.ScoreCard
        ports:
            - "8083:8083"
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["/app/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "Battleship.ScoreCard.dll"]
        networks:
            default:
                ipv4_address: 172.19.0.7
                aliases:
                    - scoreboard.internal.visualsanity.io

    battleship.game:
        image: ${DOCKER_REGISTRY-}battleshipgame
        restart: on-failure
        build:
          context: .
          dockerfile: Battleship.Game/Dockerfile
        container_name: battleship.Game
        ports:
            - "8082:8082"
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["/app/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "Battleship.Game.dll"]
        networks:
            default:
                ipv4_address: 172.19.0.6
                aliases:
                    - game.internal.visualsanity.io

    battleship.audit:
        image: ${DOCKER_REGISTRY-}battleshipaudit
        restart: on-failure
        build:
          context: .
          dockerfile: Battleship.Audit/Dockerfile
        container_name: battleship.audit
        ports:
            - "8085:8085"
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["/app/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "Battleship.Audit.dll"]
        networks:
            default:
                ipv4_address: 172.19.0.5
                aliases:
                    - audit.internal.visualsanity.io

    battleship.player:
        image: ${DOCKER_REGISTRY-}battleshipplayer
        restart: on-failure
        build: 
            context: .
            dockerfile: Battleship.Player/Dockerfile
        container_name: battleship.player
        ports:
            - "8081:8081"
        depends_on:
            - db
            - rabbitmq
        entrypoint: ["/app/wait-for-it.sh", "db:1433", "-t", "120", "--", "dotnet", "Battleship.Player.dll"]
        networks:
            default:
                ipv4_address: 172.19.0.4
                aliases:
                    - player.internal.visualsanity.io
    
    rabbitmq:
        image: 'rabbitmq:3.8.4-management-alpine'
        container_name: battleship.rabbitmq
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "25672:25672"
            - "15671:15671"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=guest   
            - RABBITMQ_DEFAULT_PASS=guest
        healthcheck:
            test: [ "CMD", "curl", "-f", "localhost", "5672" ]
            interval: 5s
            timeout: 15s
            retries: 1
        networks:
            default:
                ipv4_address: 172.19.0.3
                aliases:
                    - messaging.internal.visualsanity.io
    
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        container_name: battleship.sqlserver
        environment:
            SA_PASSWORD: "T3st_1ng"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        healthcheck:
            test: [ "CMD", "curl", "-f", "localhost", "1433" ]
            interval: 5s
            timeout: 15s
            retries: 1
        hostname: db.internal.visualsanity.io
        networks:
            default:
                ipv4_address: 172.19.0.2
                aliases:
                    - db.internal.visualsanity.io

networks:
    default:
        ipam:
            #driver: bridge
            config:
               - subnet: "172.19.0.0/20"